### ISSUE TITLE
Cannot compile an array of objects

### ISSUE THREAD

**Issue by dawaltconley** [AS-Devs/json2scss-map#2]
Seems to be a regression from [json-sass](https://github.com/acdlite/json-sass). 

On version 1.4.1:

```json
{
  "array": [
    { "foo": "bar" },
    { "baz": 4 }
  ]
}
```
Returns
```scss
(
  "array": ([object Object], [object Object])
);
```

**Comment by susanta96** [comment]
I was not active for some time. however, thank you for this issue & PR. will check soon & merge it. I'm also working on some new features after this.
