### ISSUE TITLE
How to keep the color scheme in CLI?

### ISSUE THREAD

**Issue by sneko** [AS-Devs/json2scss-map#6]
Hi,

By default all my hexas will become "hsl" whereas I want to keep my old behavior (coming from `json-sass` ;) ). I did not succeed in using something like:
```
json2scss-map --colorConversion false -i ./src/styles/xxxxx.json -o ./src/styles/xxxxxx.scss
```

or
```
json2scss-map --convertTo 'hex' false -i ./src/styles/xxxxx.json -o ./src/styles/xxxxxx.scss
```
_(I tried `--convertTo 'hex'` `--convertTo hex` `--convertTo HEX`)_

Do you know if that's possible?

Thank you,

**Comment by susanta96** [comment]
Okay. I don't think I have updated the CLI commands, however , there might be easy fix. I will let you know .

**Comment by susanta96** [comment]
Or I would update the package to support CLI properly

**Comment by ThatGuyCND** [comment]
I really wanted to use this for my project as a CLI tool — very open to feedback on my linked MR.

**Comment by susanta96** [comment]
Its awesome that you went through this to fix it. I will definitely check on your PR. If, everything is working perfectly, i would be happy to merge your PR, will create a new release. Give me 3 to 4 days.

**Comment by ThatGuyCND** [comment]
@susanta96 do you know when you might tag a new release version that includes this update?

**Comment by susanta96** [comment]
Hi @ThatGuyCND sorry for the delay. By tomorrow I will release a new version on NPM.
